on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: eventosdahoraacr.azurecr.io
        username: ${{ secrets.acr_eventosdahoraacr_username }}
        password: ${{ secrets.acr_eventosdahoraacr_password }}
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn package -Pnative -Dquarkus.native.container-build=true
       
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "src/main/docker/Dockerfile.native" -t eventosdahoraacr.azurecr.io/eventosdahoraakscluster:${{ github.sha }}
        docker push eventosdahoraacr.azurecr.io/eventosdahoraakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_eventosdahoraakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep eventosdahoraakscluster2384 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace eventosdahoraakscluster2384`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: eventosdahoraakscluster2384
        container-registry-url: eventosdahoraacr.azurecr.io
        container-registry-username: ${{ secrets.acr_eventosdahoraacr_username }}
        container-registry-password: ${{ secrets.acr_eventosdahoraacr_password }}
        secret-name: eventosdahordockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: eventosdahoraakscluster2384
        manifests: |
          "$GITHUB_WORKSPACE"/target/kubernetes/kubernetes.yml
        images: |
          eventosdahoraacr.azurecr.io/eventosdahoraakscluster:${{ github.sha }}
        imagepullsecrets: |
          eventosdahordockerauth
